Setup publishing the artifacts to the Bintray maven repository
ACCULA/IdeaClonePlugin pull request #1
Opened 2020-07-20 22:39 UTC by lamtev

* Setup publishing the artifacts to the Bintray maven repository
* Make `jar` Gradle task assemble a fat Jar with all dependencies included
* Remove all unnecessary dependencies
* Update README with instructions on how to use all this stuff

2020-07-21 22:21 UTC, VanyaKrylov requested changes

2020-07-21 22:21 UTC, VanyaKrylov commented on build.gradle
> +    implementation files("lib/kovenant-core-3.3.0.jar")
Remove redundant dependency

2020-07-21 22:21 UTC, VanyaKrylov commented on build.gradle
> +    implementation files("lib/union-find-set-1.0.jar")
Redundant as well - remove

2020-07-21 22:21 UTC, VanyaKrylov commented on build.gradle
> +    implementation files("lib/suffixtree-0.1.jar")
Replace with implementation("com.suhininalex:suffixtree:1.0.2")

2020-07-21 23:25 UTC, lamtev commented on build.gradle
> +    implementation files("lib/kovenant-core-3.3.0.jar")
done

2020-07-21 23:25 UTC, lamtev commented on build.gradle
> +    implementation files("lib/union-find-set-1.0.jar")
done

2020-07-21 23:25 UTC, lamtev commented on build.gradle
> +    implementation files("lib/suffixtree-0.1.jar")
done

2020-07-22 09:10 UTC, VanyaKrylov approved these changes

2020-07-22 09:30 UTC, merged